### ISSUE TITLE
Line 27: (h – 2*cy)/h

### ISSUE THREAD

**Issue by Oliviervintecc** [francoisruty/fruty_opencv-opengl-projection-matrix#1]
Hello,

First of all thanks for the tutorial it was very handy.
After a lot of debugging and testing I think Line 27 (h– 2*cy)/h should have a minus in front of it.
This gave me the exact results, the term (h– 2*cy)/h is usually very small (in your example code it is 0)
In my test case the minus error gave a 16 pixel translation which was unwanted.

**Comment by francoisruty** [comment]
thanks a lot for your feedback, I just made this change, it's on branch master!
